[profile.default]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.ci]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.lite]
solc = "0.8.28"
optimizer = true
optimizer_runs = 1
via_ir = true
